#!/bin/bash
#
# Input: <word><tab><count>
# Output: <word><tab><total>

# Artificial latency, random between 1 - 3 seconds
# If developing locally on Mac, use gshuf instead of shuf
# Refer to this for more info: https://apple.stackexchange.com/questions/142860/install-shuf-on-os-x

SHUF = shuf
# If shuf is not found on this computer then use gshuf (for OSX)
if ! type shuf 2> /dev/null; then
  SHUF=gshuf
fi

SLEEP_TIME=`$SHUF -i 1-4 -n 1`
sleep $SLEEP_TIME

# WARNING: this code assumes that the value is "1" for every key!!!
cat | cut -f1 | uniq -c | awk '{print $2"\t"$1}'
